<a href="https://colab.research.google.com/github/tether007/SciKit-Basics/blob/main/Pytorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Fundamentals of pytorch**
ref notebook="https://www.learnpytorch.io/00_pytorch_fundamentals/"

In [1]:
import torch
import pandas as py
import matplotlib as mp
import numpy as np
print(torch.__version__)

2.5.0+cu121


In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#getting tensor as int
scalar.item()

7

In [5]:
#Vector
vector=torch.tensor([9,6])
vector

tensor([9, 6])

In [6]:
torch.Size([2])

torch.Size([2])

In [38]:
#Matrix
MATRIX=torch.tensor([[2,3],
                    [3,4]])
MATRIX
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([2, 3])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [42]:
#TENSOR
TENSOR = torch.tensor([[1,2,3],[4,3,5]])
TENSOR

tensor([[1, 2, 3],
        [4, 3, 5]])

In [43]:
TENSOR.ndim

2

In [30]:
TENSOR1=torch.tensor([[[1,3],[2,3]]])
TENSOR1.shape

torch.Size([1, 2, 2])

### **RANDOM TENSORS**
Random tensors are imp as NN(neural networs)genarally use these and keep on iterate the numbers to make a representation
TORCH random-->"https://pytorch.org/docs/stable/generated/torch.rand.html"

In [37]:
random_tensor=torch.rand(3,4)
random_tensor


tensor([[0.1942, 0.8367, 0.2933, 0.9162],
        [0.4689, 0.5499, 0.1992, 0.5727],
        [0.6004, 0.6309, 0.8463, 0.9278]])

In [ ]:
#Create a random tensor similar shape to an image tensor
rand_image_size_tensor=torch.rand(size=(3,244,244))#size or doesnt matter on n the same
#here 3 is no:of color channels ie R G B and 244,244 are Height n bredth
rand_image_size_tensor

### **ZEROS AND ONES**

In [46]:
zeros=torch.zeros(size=(3,4))

In [47]:
ones=torch.ones(size=(3,4))

In [51]:
zeros*ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [53]:
ones.dtype#default type of tensors are float

torch.float32

### CREATING A RANGE OF TENSORS n TENSORS-LIKE

In [62]:
one_to_10=torch.arange(0,10)
one_to_10
one_t0_1000=torch.arange(1,1000,19)#(start,end,step)
one_t0_1000

tensor([  1,  20,  39,  58,  77,  96, 115, 134, 153, 172, 191, 210, 229, 248,
        267, 286, 305, 324, 343, 362, 381, 400, 419, 438, 457, 476, 495, 514,
        533, 552, 571, 590, 609, 628, 647, 666, 685, 704, 723, 742, 761, 780,
        799, 818, 837, 856, 875, 894, 913, 932, 951, 970, 989])

In [66]:
# creating tensors like
ten_zeros = torch.ones_like(one_to_10)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### TENSOR DATATYPES

In [71]:
#float 32 tensor
f_32_tensor=torch.tensor([[[1,3,4],[2,3,4]]],dtype=None,#tensor's datatype
                         device=None,#d
                         requires_grad=False)

In [73]:
f_32_tensor

tensor([[[1, 3, 4],
         [2, 3, 4]]])